### ISSUE TITLE
regression related to Reply-to header recently added

### ISSUE THREAD

**Issue by nsitbon** [mailjet/wordpress-mailjet-plugin-apiv3#30]
Hi, I spent some times yesterday to find why helpscout was misrecognizing the sender of the email sent by contact-form 7 plugin via the mailjet wordpress plugin (last version). I found the bug was introduced with this commit https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/commit/14b2518c6eff28ac34c54e149336a92071e000f3 where you add a `Reply-To` header without looking if anyone already exists which is the case for me (contact-form 7 adds a `Reply-To` header).
I fixed it temporarily by commenting the line but I'm waiting for a more reliable fix from you.
Thanks guys.

**Comment by ddxb** [comment]
Thanks nsitbon!
I'll have the team take a look at your comment so we can correct this on a permanent basis.  
Keep you posted.
Cheers,
Stephen

**Comment by yasen-mailjet** [comment]
Hi @nsitbon, 

I've fixed the issue with commit
https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/commit/a0ac20f4576ec9df91adebcc4cdb1419773993db

Thanks for reporting it.

**Comment by nsitbon** [comment]
Well done!
Big thanks for you reactivity.

**Comment by nsitbon** [comment]
Hi, I'm reopening this issue because the bug is still present despite the fix. I had to once again comment the line adding the admin email in the reply-to header.

**Comment by yasen-mailjet** [comment]
@nsitbon what is your PHP version?

**Comment by nsitbon** [comment]
Hi @yasen-mailjet my PHP version is 5.6.7 and my web server is nginx 1.6.2.

**Comment by yasen-mailjet** [comment]
Hi @nsitbon, I'm testing the setting of headers. I've set the code to dump the phpmailer object instance:
```
        // Add reply to header only if one does not already exist in the PhpMailer properties CustomerHeader and ReplyTo
        // This check would work only for php >= 5.3
        $hasReplyTo = $this->_getPhpMailerProperties($phpmailer, 'ReplyTo');
var_dump($phpmailer);        
        if (!$this->_customHeaderHasReplyTo($this->_getPhpMailerProperties($phpmailer, 'CustomHeader')) && empty($hasReplyTo)){
            $phpmailer->addReplyTo(get_option('admin_email'));
        }
		$phpmailer->AddCustomHeader($this->api->mj_mailer);
var_dump($phpmailer);die;  
```
The first dump shows:
https://gist.github.com/yasen-mailjet/aff4fdbe4557ebdba380
and the 2nd one:
https://gist.github.com/yasen-mailjet/c4d24a8423c8f931fbba

These dumps show that our code does not add additional headers when it recognizes that there is either ReplyTo header or custom ReplyTo header.

**Comment by nsitbon** [comment]
I think the problem is that there is no ReplyTo header already added, the sender of the mail only use the From header then you're adding the ReplyTo which is obviously wrong.
Can you just drop this feature because it breaks existing code and behaviour ?

**Comment by aneliyaB** [comment]
Hi, 
Thank you for your feedback.
In fact as you can see from our previous comment and in the dump which shows that before Reply-To check we have the following data in the phpmailer object : 
["ReplyTo":protected]=>
  array(o) {
  }
["CustomHeader":protected]=>
  array(1) {
    [0]=>
    array(2) {
      [0]=>
      string(music) "Reply-To"
      [1]=>
      string(22) " mail@gmail.com"
    }
  }

This shows that the plugin Contact Form 7 has already added the Reply-To header so it means that we were not suppose to add it additionally.

**Comment by nsitbon** [comment]
Ok sorry for the delay, after investigating further I have the same problem with my Woocommerce plugin : 
your setting the admin email as the Reply-To but woo commerce has its own email to manage the shop so all the email sent by woocommerce have a bad Reply-To email. I once again have to comment the following line
```php
//            $phpmailer->addReplyTo(get_option('admin_email'));
```
please guys can you stop adding this header because it cause me lots of trouble with my clients.
I am the admin of a big wordpress multisite installation with tons of shop running on woo commerce and all their clients receive email "coming" from me.

**Comment by nsitbon** [comment]
Thanks guys for merging my PR I just saw the new plugin version released
