### ISSUE TITLE
5.2.7 release - php error MailjetSettings.php on line 339

### ISSUE THREAD

**Issue by wurldit** [mailjet/wordpress-mailjet-plugin-apiv3#303]
after updating the plugin the following error occured

[12-May-2021 07:06:30 UTC] PHP Parse error:  syntax error, unexpected ')' in /home/*****/web/*****/public_html/wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetSettings.php on line 339

**Comment by uavn** [comment]
fixed

**Comment by wurldit** [comment]
still not fixed, after new plugin

[12-May-2021 09:04:22 UTC] PHP Parse error:  syntax error, unexpected ')' in /home/../web/.../public_html/wp-content/plugins/mailjet-for-wordpress/src/widget/WP_Mailjet_Subscribe_Widget.php on line 297

**Comment by uavn** [comment]
pardon, this it the other place, fixed now
